"""End-to-end inference pipeline for the Outfit Vibe Recommender.

This is the notebook logic (notebooks 02, 04, 05, 06-inference, 07, 08) refactored into
importable functions so the Streamlit app and any script can share one code path.

Nothing here trains anything. The usage classifier is trained in
``notebooks/06_usage_classifier.ipynb`` and only loaded for inference here. The item-pool
embeddings are built once in ``notebooks/03_item_embeddings.ipynb`` and cached to
``data/embeddings/``; this module reads that cache and never recomputes it.

Prerequisites (generated by the notebooks, git-ignored):
  data/embeddings/item_embeddings.npy   item_ids.npy   usage_classifier.pt

Run ``python -m src.pipeline`` to analyze the images in ``data/board_images/`` from the CLI.
"""

from __future__ import annotations

import os
from dataclasses import dataclass, field
from pathlib import Path
from urllib.parse import quote_plus

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
from PIL import Image

MODEL_NAME = "patrickjohncyh/fashion-clip"
EMBED_DIM = 512

PROJECT_ROOT = Path(__file__).resolve().parents[1]
EMBED_DIR = PROJECT_ROOT / "data" / "embeddings"
BOARD_DIR = PROJECT_ROOT / "data" / "board_images"

ITEM_EMBEDDINGS_PATH = EMBED_DIR / "item_embeddings.npy"
ITEM_IDS_PATH = EMBED_DIR / "item_ids.npy"
CLASSIFIER_PATH = EMBED_DIR / "usage_classifier.pt"

IMAGE_SUFFIXES = {".jpg", ".jpeg", ".png", ".webp"}

# ---------------------------------------------------------------------------
# Vocabularies (kept identical to notebooks 05 and 07)
# ---------------------------------------------------------------------------

AESTHETIC_LABELS = [
    "cottagecore", "dark academia", "y2k", "minimalist", "streetwear",
    "preppy", "grunge", "bohemian", "athleisure", "old money",
    "coquette", "gorpcore", "clean girl", "coastal grandmother",
    "punk", "romantic", "androgynous", "vintage", "glam",
]
AESTHETIC_PROMPT_TEMPLATE = "a photo of an outfit in the {} aesthetic"

GARMENT_VOCAB: dict[str, list[str]] = {
    "Silhouette/fit": ["oversized", "cropped", "fitted", "high-waisted", "wide-leg", "bodycon", "baggy"],
    "Neckline/sleeve": ["off the shoulder", "halter", "puff sleeve", "spaghetti strap", "turtleneck", "square neck"],
    "Fabric/texture": ["sheer", "satin", "corduroy", "mesh", "knit", "denim", "leather", "velvet"],
    "Pattern/finish": ["pastel", "plaid", "floral", "metallic", "distressed", "ribbed"],
}
GARMENT_PROMPT_TEMPLATE = "a photo of clothing that is {}"

MIN_PHOTOS_PER_CATEGORY = 20  # below this the averaged category centroid is too noisy to trust
NECKLINE_CAPABLE_SUBCATEGORIES = {"Topwear", "Innerwear", "Dress"}

# ---------------------------------------------------------------------------
# Depop query construction (kept identical to notebook 08)
# ---------------------------------------------------------------------------

DEPOP_SEARCH_BASE = "https://www.depop.com/search/"

# Kaggle articleType -> the word a Depop seller would actually put in a listing title.
DEPOP_NOUN = {
    "Tshirts": "tee", "Tops": "top", "Shirts": "shirt", "Camisoles": "cami",
    "Tunics": "tunic top", "Dresses": "dress", "Shorts": "shorts", "Jeans": "jeans",
    "Trousers": "trousers", "Track Pants": "joggers", "Capris": "cropped trousers",
    "Leggings": "leggings", "Skirts": "skirt", "Jackets": "jacket", "Blazers": "blazer",
    "Sweaters": "knit jumper", "Sweatshirts": "sweatshirt",
}

# Detail terms that merely restate their category noun ("cropped shorts", "knit sweater").
# The plausibility gate only removes physically-impossible terms, not redundant ones.
REDUNDANT_FOR = {
    "Shorts": {"cropped"},
    "Camisoles": {"cropped", "fitted", "spaghetti strap"},
    "Tunics": {"cropped"},
    "Leggings": {"fitted", "bodycon"},
    "Sweaters": {"knit"},
    "Jeans": {"denim"},
}


# ---------------------------------------------------------------------------
# Model loading + embedding helpers
# ---------------------------------------------------------------------------

def get_device() -> str:
    """MPS on Apple Silicon, else CPU (the datasets here are small enough for CPU)."""
    return "mps" if torch.backends.mps.is_available() else "cpu"


def load_fashion_clip(device: str | None = None):
    """Load pretrained FashionCLIP. Returns ``(model, processor, device)``."""
    from transformers import CLIPModel, CLIPProcessor

    device = device or get_device()
    model = CLIPModel.from_pretrained(MODEL_NAME).to(device)
    model.eval()
    processor = CLIPProcessor.from_pretrained(MODEL_NAME)
    return model, processor, device


def _pooled(outputs):
    """``get_image_features`` / ``get_text_features`` return a pooled-output object on
    transformers >= 5; older versions returned a bare tensor. Handle both."""
    return getattr(outputs, "pooler_output", outputs)


def embed_images(images, model, processor, device: str) -> np.ndarray:
    """Embed PIL images (or image paths) one at a time. Returns ``(n, EMBED_DIM)``, unnormalized."""
    vectors = []
    for image in images:
        if not isinstance(image, Image.Image):
            image = Image.open(image)
        image = image.convert("RGB")
        inputs = processor(images=image, return_tensors="pt").to(device)
        with torch.no_grad():
            out = model.get_image_features(**inputs)
        vectors.append(_pooled(out)[0].cpu().numpy())
    return np.stack(vectors)


def board_vibe_vector(images, model, processor, device: str) -> np.ndarray:
    """Average every board image's embedding into one L2-normalized "vibe" vector.

    Same as notebook 02: each image is one data point describing part of the board's
    aesthetic; averaging blends them into a single summary vector.
    """
    embeddings = embed_images(images, model, processor, device)
    vibe = embeddings.mean(axis=0)
    return vibe / np.linalg.norm(vibe)


def embed_text_terms(terms, template, model, processor, device: str) -> np.ndarray:
    """Embed each term wrapped in ``template`` (CLIP prompt engineering). Rows are
    L2-normalized, so a dot product against a unit vector is the cosine similarity."""
    prompts = [template.format(term) for term in terms]
    inputs = processor(text=prompts, return_tensors="pt", padding=True).to(device)
    with torch.no_grad():
        out = model.get_text_features(**inputs)
    vecs = _pooled(out).cpu().numpy()
    return vecs / np.linalg.norm(vecs, axis=1, keepdims=True)


# ---------------------------------------------------------------------------
# Kaggle dataset access
# ---------------------------------------------------------------------------

def find_dataset_root(explicit: str | os.PathLike | None = None) -> Path:
    """Locate the cached Kaggle "Fashion Product Images (Small)" folder.

    Checks, in order: the explicit argument, ``$KAGGLE_FASHION_DIR``, then the
    default kagglehub cache location.
    """
    candidates = []
    if explicit:
        candidates.append(Path(explicit))
    if os.environ.get("KAGGLE_FASHION_DIR"):
        candidates.append(Path(os.environ["KAGGLE_FASHION_DIR"]))
    cache_base = Path.home() / ".cache/kagglehub/datasets/paramaggarwal/fashion-product-images-small/versions"
    if cache_base.is_dir():
        candidates.extend(sorted(cache_base.iterdir(), reverse=True))

    for root in candidates:
        if (root / "styles.csv").is_file() and (root / "images").is_dir():
            return root

    raise FileNotFoundError(
        "Could not find the Kaggle dataset. Run notebooks/01_load_data.ipynb to download it, "
        "or set KAGGLE_FASHION_DIR to the folder containing styles.csv and images/."
    )


def load_styles(dataset_root: Path) -> pd.DataFrame:
    """``styles.csv`` indexed by item id. Skips the handful of comma-mangled rows."""
    df = pd.read_csv(dataset_root / "styles.csv", on_bad_lines="skip")
    return df.set_index("id")


def load_item_pool() -> tuple[np.ndarray, np.ndarray]:
    """The cached item-pool embeddings and their aligned ids (from notebook 03)."""
    if not ITEM_EMBEDDINGS_PATH.is_file() or not ITEM_IDS_PATH.is_file():
        raise FileNotFoundError(
            f"Missing cached item embeddings in {EMBED_DIR}. "
            "Run notebooks/03_item_embeddings.ipynb first (≈10 min, one time)."
        )
    return np.load(ITEM_EMBEDDINGS_PATH), np.load(ITEM_IDS_PATH)


# ---------------------------------------------------------------------------
# Step 6 — item recommendations
# ---------------------------------------------------------------------------

def recommend_items(
    vibe: np.ndarray,
    item_embeddings: np.ndarray,
    item_ids: np.ndarray,
    styles_df: pd.DataFrame,
    top_n: int = 15,
) -> pd.DataFrame:
    """Rank the item pool by cosine similarity to the vibe vector; return the top ``top_n``.

    Result is indexed by item id with columns: productDisplayName, articleType,
    baseColour, usage, similarity — ordered best match first.
    """
    item_norms = np.linalg.norm(item_embeddings, axis=1)
    sims = (item_embeddings @ vibe) / (item_norms * np.linalg.norm(vibe))

    top_idx = np.argsort(-sims)[:top_n]
    top_ids = item_ids[top_idx]

    cols = ["productDisplayName", "articleType", "baseColour", "usage"]
    out = styles_df.reindex(top_ids)[cols].copy()
    out["similarity"] = sims[top_idx]
    out.index.name = "id"
    return out


# ---------------------------------------------------------------------------
# Step 7 — zero-shot aesthetic tags
# ---------------------------------------------------------------------------

def rank_by_similarity(vibe: np.ndarray, term_embeddings: np.ndarray, terms) -> list[tuple[str, float]]:
    """``(term, cosine_similarity)`` pairs, sorted most similar first.

    ``term_embeddings`` rows are unit length, so the dot product is the cosine similarity.
    """
    sims = term_embeddings @ vibe
    order = np.argsort(-sims)
    return [(terms[i], float(sims[i])) for i in order]


def aesthetic_tags(vibe: np.ndarray, model, processor, device: str) -> list[tuple[str, float]]:
    """Broad style tags (cottagecore, y2k, ...) ranked by similarity to the board."""
    label_embeddings = embed_text_terms(AESTHETIC_LABELS, AESTHETIC_PROMPT_TEMPLATE, model, processor, device)
    return rank_by_similarity(vibe, label_embeddings, AESTHETIC_LABELS)


# ---------------------------------------------------------------------------
# Step 9 — garment-detail terms + per-category plausibility gate
# ---------------------------------------------------------------------------

def flat_garment_terms() -> tuple[list[str], list[str]]:
    """Flatten GARMENT_VOCAB into aligned ``(terms, group_of_each_term)`` lists."""
    terms, groups = [], []
    for group, words in GARMENT_VOCAB.items():
        for word in words:
            terms.append(word)
            groups.append(group)
    return terms, groups


def build_category_gate(
    item_embeddings: np.ndarray,
    item_ids: np.ndarray,
    styles_df: pd.DataFrame,
    term_embeddings: np.ndarray,
    terms: list[str],
    term_groups: list[str],
) -> dict[str, dict]:
    """For each clothing category, the subset of garment-detail terms that plausibly apply.

    Board-independent — depends only on the item pool and the fixed vocabulary — so the app
    computes this once. Two grounded signals (see notebook 07):

    1. Hard rule: a category whose dominant ``subCategory`` isn't Topwear/Innerwear/Dress
       physically has no neckline or sleeve, so every Neckline/sleeve term is stripped.
    2. Centroid median: among terms surviving rule 1, keep only those scoring at or above
       the category's own median term score (centroid = mean embedding of its real photos).
    """
    categories = styles_df.reindex(item_ids)["articleType"].to_numpy()
    counts = pd.Series(categories).value_counts()

    kept_names, centroids = [], []
    for category, count in counts.items():
        if count < MIN_PHOTOS_PER_CATEGORY:
            continue
        centroid = item_embeddings[categories == category].mean(axis=0)
        centroids.append(centroid / np.linalg.norm(centroid))
        kept_names.append(category)

    centroid_matrix = np.stack(centroids)                      # (n_categories, EMBED_DIM)
    term_vs_category = term_embeddings @ centroid_matrix.T      # (n_terms, n_categories)

    dominant_sub = styles_df.groupby("articleType")["subCategory"].agg(lambda s: s.value_counts().idxmax())
    neckline_terms = {terms[i] for i in range(len(terms)) if term_groups[i] == "Neckline/sleeve"}

    gate: dict[str, dict] = {}
    for col, category in enumerate(kept_names):
        scores = term_vs_category[:, col]
        threshold = float(np.median(scores))
        passed = [terms[i] for i in range(len(terms)) if scores[i] >= threshold]
        if dominant_sub.get(category) not in NECKLINE_CAPABLE_SUBCATEGORIES:
            passed = [t for t in passed if t not in neckline_terms]
        gate[category] = {"threshold": threshold, "passed_terms": passed}
    return gate


# ---------------------------------------------------------------------------
# Step 8 (inference only) — trained usage classifier
# ---------------------------------------------------------------------------

class UsageClassifier(nn.Module):
    """512 -> 128 -> 5 feed-forward head trained on frozen embeddings (notebook 06)."""

    def __init__(self, input_dim: int = EMBED_DIM, hidden_dim: int = 128, num_classes: int = 5):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(input_dim, hidden_dim),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(hidden_dim, num_classes),
        )

    def forward(self, x):
        return self.net(x)


@dataclass
class LoadedClassifier:
    model: UsageClassifier
    class_names: list[str]
    scaler_mean: np.ndarray
    scaler_scale: np.ndarray


def load_usage_classifier(path: Path = CLASSIFIER_PATH) -> LoadedClassifier:
    if not path.is_file():
        raise FileNotFoundError(
            f"Missing {path}. Run notebooks/06_usage_classifier.ipynb to train and save it."
        )
    ckpt = torch.load(path, weights_only=False, map_location="cpu")
    model = UsageClassifier(ckpt["input_dim"], ckpt["hidden_dim"], ckpt["num_classes"])
    model.load_state_dict(ckpt["model_state_dict"])
    model.eval()
    return LoadedClassifier(
        model=model,
        class_names=list(ckpt["class_names"]),
        scaler_mean=np.asarray(ckpt["scaler_mean"]),
        scaler_scale=np.asarray(ckpt["scaler_scale"]),
    )


def predict_usage(vibe: np.ndarray, clf: LoadedClassifier) -> list[tuple[str, float]]:
    """Run the board's vibe vector through the trained head.

    Applies the same standardization the training data used (the model only ever saw
    scaled inputs). Returns ``(class_name, probability)`` sorted most likely first.
    """
    scaled = (vibe - clf.scaler_mean) / clf.scaler_scale
    with torch.no_grad():
        logits = clf.model(torch.tensor(scaled, dtype=torch.float32).unsqueeze(0))
        probs = F.softmax(logits, dim=1)[0].numpy()
    order = np.argsort(-probs)
    return [(clf.class_names[i], float(probs[i])) for i in order]


# ---------------------------------------------------------------------------
# Step 10 — Depop link generation
# ---------------------------------------------------------------------------

def depop_noun(article_type: str) -> str:
    return DEPOP_NOUN.get(article_type, article_type.lower())


def top_detail_term(article_type: str, ranked_terms: list[tuple[str, float]], category_gate: dict) -> str | None:
    """Highest board-relevance garment-detail term that (a) passes this category's
    plausibility gate and (b) doesn't just restate the category noun. ``None`` if nothing qualifies."""
    gate = category_gate.get(article_type)
    passed = set(gate["passed_terms"]) if gate is not None else None
    redundant = REDUNDANT_FOR.get(article_type, set())
    for term, _score in ranked_terms:
        if passed is not None and term not in passed:
            continue
        if term in redundant:
            continue
        return term
    return None


def build_query(article_type: str, top_aesthetic: str, ranked_terms, category_gate: dict) -> str:
    """``{aesthetic} {one detail term} {Depop noun}`` — e.g. ``clean girl ribbed tee``."""
    parts = [top_aesthetic]
    detail = top_detail_term(article_type, ranked_terms, category_gate)
    if detail:
        parts.append(detail)
    parts.append(depop_noun(article_type))
    return " ".join(parts)


def depop_url(query: str) -> str:
    return f"{DEPOP_SEARCH_BASE}?q={quote_plus(query)}"


def generate_depop_links(
    recommendations: pd.DataFrame,
    top_aesthetic: str,
    ranked_terms: list[tuple[str, float]],
    category_gate: dict,
) -> pd.DataFrame:
    """One Depop search per recommended item, then de-duplicated.

    Returns rows of: query, url, covers (list of product names that map to that query).
    """
    df = recommendations.copy()
    df["query"] = df["articleType"].apply(lambda a: build_query(a, top_aesthetic, ranked_terms, category_gate))
    df["url"] = df["query"].apply(depop_url)

    grouped = df.groupby("query", sort=False)
    return pd.DataFrame({
        "query": list(grouped.groups.keys()),
        "url": grouped["url"].first().tolist(),
        "covers": grouped["productDisplayName"].apply(list).tolist(),
    })


# ---------------------------------------------------------------------------
# Orchestration
# ---------------------------------------------------------------------------

@dataclass
class BoardAnalysis:
    vibe: np.ndarray
    aesthetic_tags: list[tuple[str, float]]        # (tag, score), ranked
    usage_prediction: list[tuple[str, float]]      # (class, probability), ranked
    garment_terms: list[tuple[str, float]]         # (term, score), ranked
    recommendations: pd.DataFrame                  # indexed by item id
    depop_links: pd.DataFrame                      # query / url / covers
    dataset_root: Path = field(repr=False)

    @property
    def top_aesthetic(self) -> str:
        return self.aesthetic_tags[0][0]

    @property
    def predicted_usage(self) -> str:
        return self.usage_prediction[0][0]

    def item_image_path(self, item_id: int) -> Path:
        return self.dataset_root / "images" / f"{item_id}.jpg"


def analyze_board(
    images,
    *,
    model,
    processor,
    device: str,
    item_embeddings: np.ndarray,
    item_ids: np.ndarray,
    styles_df: pd.DataFrame,
    classifier: LoadedClassifier,
    category_gate: dict,
    dataset_root: Path,
    top_n_items: int = 15,
) -> BoardAnalysis:
    """Full board -> recommendations + tags + Depop links. Callers own the (cached) resources."""
    vibe = board_vibe_vector(images, model, processor, device)

    tags = aesthetic_tags(vibe, model, processor, device)

    terms, groups = flat_garment_terms()
    term_embeddings = embed_text_terms(terms, GARMENT_PROMPT_TEMPLATE, model, processor, device)
    ranked_terms = rank_by_similarity(vibe, term_embeddings, terms)

    usage = predict_usage(vibe, classifier)
    recs = recommend_items(vibe, item_embeddings, item_ids, styles_df, top_n=top_n_items)
    links = generate_depop_links(recs, tags[0][0], ranked_terms, category_gate)

    return BoardAnalysis(
        vibe=vibe,
        aesthetic_tags=tags,
        usage_prediction=usage,
        garment_terms=ranked_terms,
        recommendations=recs,
        depop_links=links,
        dataset_root=dataset_root,
    )


def list_board_images(folder: Path = BOARD_DIR) -> list[Path]:
    return sorted(p for p in folder.iterdir() if p.suffix.lower() in IMAGE_SUFFIXES)


def _cli() -> None:
    """Analyze data/board_images/ and print the same summary as notebook 08."""
    paths = list_board_images()
    if not paths:
        raise SystemExit(f"No images in {BOARD_DIR}. Add some board images and re-run.")

    print(f"Loading FashionCLIP and cached data ({len(paths)} board images)...")
    model, processor, device = load_fashion_clip()
    item_embeddings, item_ids = load_item_pool()
    dataset_root = find_dataset_root()
    styles_df = load_styles(dataset_root)
    classifier = load_usage_classifier()

    terms, groups = flat_garment_terms()
    term_embeddings = embed_text_terms(terms, GARMENT_PROMPT_TEMPLATE, model, processor, device)
    category_gate = build_category_gate(item_embeddings, item_ids, styles_df, term_embeddings, terms, groups)

    analysis = analyze_board(
        [Image.open(p) for p in paths],
        model=model, processor=processor, device=device,
        item_embeddings=item_embeddings, item_ids=item_ids, styles_df=styles_df,
        classifier=classifier, category_gate=category_gate, dataset_root=dataset_root,
    )

    print("\n" + "=" * 64)
    print("BOARD VIBE SUMMARY")
    print("=" * 64)
    top5 = ", ".join(t for t, _ in analysis.aesthetic_tags[:5])
    print(f"Top aesthetic:       {analysis.top_aesthetic}   (top 5: {top5})")
    print(f"Predicted usage:     {analysis.predicted_usage}")
    print(f"Board garment terms: {', '.join(t for t, _ in analysis.garment_terms[:5])}")
    print(f"\n{len(analysis.depop_links)} unique Depop searches for "
          f"{len(analysis.recommendations)} recommended items:\n")
    for row in analysis.depop_links.itertuples(index=False):
        print(f'  "{row.query}"')
        print(f"    {row.url}")
        print(f"    covers: {', '.join(row.covers)}\n")


if __name__ == "__main__":
    _cli()
